export type ToolCategory = "dev" | "design" | "product" | "fun";

export interface ToolMeta {
  id: string;
  number: string;
  name: string;
  description: string;
  href: string;
  category: ToolCategory;
  keywords: string[];
}

export const TOOLS: ToolMeta[] = [
  // Dev Tools
  {
    id: "json-formatter",
    number: "001",
    name: "JSON Formatter",
    description: "Prettify, validate or minify JSON.",
    href: "/json-formatter",
    category: "dev",
    keywords: ["json", "prettify", "validate", "minify", "format", "dev"],
  },
  {
    id: "encode-decode",
    number: "002",
    name: "Encode/Decode",
    description: "Base64 and URL encoding/decoding.",
    href: "/encode-decode",
    category: "dev",
    keywords: ["base64", "url", "encode", "decode", "dev"],
  },
  {
    id: "case-converter",
    number: "003",
    name: "Case Converter",
    description: "Convert text between camelCase, snake_case, etc.",
    href: "/case-converter",
    category: "dev",
    keywords: ["case", "camel", "snake", "kebab", "convert", "dev"],
  },
  {
    id: "timestamp-converter",
    number: "004",
    name: "Timestamp Converter",
    description: "Convert epoch timestamps to human-readable dates.",
    href: "/timestamp-converter",
    category: "dev",
    keywords: ["time", "timestamp", "epoch", "date", "dev"],
  },
  {
    id: "sql-formatter",
    number: "005",
    name: "SQL Formatter",
    description: "Format and prettify SQL queries.",
    href: "/sql-formatter",
    category: "dev",
    keywords: ["sql", "format", "query", "database", "dev"],
  },
  {
    id: "data-converter",
    number: "006",
    name: "Data Converter",
    description: "Convert between JSON, YAML, TOML, and CSV.",
    href: "/data-converter",
    category: "dev",
    keywords: ["json", "yaml", "toml", "csv", "convert", "dev"],
  },
  {
    id: "markdown-preview",
    number: "007",
    name: "Markdown Preview",
    description: "Live preview and sanitize Markdown to HTML.",
    href: "/markdown-preview",
    category: "dev",
    keywords: ["markdown", "html", "preview", "md", "dev"],
  },
  {
    id: "regex-tester",
    number: "008",
    name: "Regex Tester",
    description: "Test regular expressions with live highlights.",
    href: "/regex-tester",
    category: "dev",
    keywords: ["regex", "regular", "expression", "match", "dev"],
  },
  {
    id: "diff-viewer",
    number: "009",
    name: "Diff Viewer",
    description: "Compare two pieces of text side-by-side.",
    href: "/diff-viewer",
    category: "dev",
    keywords: ["diff", "compare", "text", "changes", "dev"],
  },
  {
    id: "jwt-decoder",
    number: "010",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens (client-side only).",
    href: "/jwt-decoder",
    category: "dev",
    keywords: ["jwt", "token", "decode", "json", "dev"],
  },
  {
    id: "keycode-inspector",
    number: "011",
    name: "Keycode Inspector",
    description: "Inspect JavaScript keyboard events and keycodes.",
    href: "/keycode-inspector",
    category: "dev",
    keywords: ["key", "keycode", "event", "keyboard", "dev"],
  },
  {
    id: "html-viewer",
    number: "012",
    name: "HTML Viewer",
    description: "Preview HTML in a sandboxed iframe.",
    href: "/html-viewer",
    category: "dev",
    keywords: ["html", "preview", "sandbox", "iframe", "dev"],
  },
  {
    id: "px-to-rem",
    number: "013",
    name: "PX to REM",
    description: "Convert pixels to rem units.",
    href: "/px-to-rem",
    category: "dev",
    keywords: ["px", "rem", "css", "convert", "dev"],
  },
  {
    id: "list-cleaner",
    number: "014",
    name: "List Cleaner",
    description: "Sort, deduplicate, and clean text lists.",
    href: "/list-cleaner",
    category: "dev",
    keywords: ["list", "sort", "dedupe", "clean", "dev"],
  },
  {
    id: "id-generator",
    number: "015",
    name: "ID & Password Generator",
    description: "Generate UUIDs and secure passwords.",
    href: "/id-generator",
    category: "dev",
    keywords: ["uuid", "password", "generate", "secure", "dev"],
  },
  {
    id: "hash-checksum",
    number: "016",
    name: "Hash & Checksum",
    description: "Calculate SHA/MD5 hashes for text and files.",
    href: "/hash-checksum",
    category: "dev",
    keywords: ["hash", "md5", "sha", "checksum", "crypto", "dev"],
  },
  {
    id: "cron-helper",
    number: "017",
    name: "Cron Helper",
    description: "Explain and calculate cron schedule expressions.",
    href: "/cron-helper",
    category: "dev",
    keywords: ["cron", "schedule", "time", "dev"],
  },
  {
    id: "http-status",
    number: "018",
    name: "HTTP Status Codes",
    description: "Lookup and filter HTTP status codes.",
    href: "/http-status",
    category: "dev",
    keywords: ["http", "status", "code", "dev"],
  },

  // Design Tools
  {
    id: "color-palette",
    number: "019",
    name: "Color Palette",
    description: "Generate and extract color palettes.",
    href: "/color-palette",
    category: "design",
    keywords: ["color", "palette", "generate", "design"],
  },
  {
    id: "color-converter",
    number: "020",
    name: "Color Converter",
    description: "Convert colors between Hex, RGB, HSL.",
    href: "/color-converter",
    category: "design",
    keywords: ["color", "convert", "hex", "rgb", "hsl", "design"],
  },
  {
    id: "contrast-checker",
    number: "021",
    name: "Contrast Checker",
    description: "Check WCAG color contrast ratios.",
    href: "/contrast-checker",
    category: "design",
    keywords: ["color", "contrast", "wcag", "accessibility", "design"],
  },
  {
    id: "gradient-studio",
    number: "022",
    name: "Gradient Studio",
    description: "Create and export CSS linear and radial gradients.",
    href: "/gradient-studio",
    category: "design",
    keywords: ["color", "gradient", "css", "design"],
  },
  {
    id: "shadow-playground",
    number: "023",
    name: "Shadow Playground",
    description: "Design and copy CSS box-shadows.",
    href: "/shadow-playground",
    category: "design",
    keywords: ["css", "shadow", "box-shadow", "design"],
  },
  {
    id: "image-tools",
    number: "024",
    name: "Image Resizer",
    description: "Resize images by custom dimensions, scale presets, or export a full favicon pack.",
    href: "/image-tools",
    category: "design",
    keywords: ["image", "resize", "scale", "favicon", "dimensions", "design"],
  },
  {
    id: "image-converter",
    number: "024b",
    name: "Image Converter",
    description: "Convert and compress images to WebP, JPEG, or PNG with quality control.",
    href: "/image-converter",
    category: "design",
    keywords: ["image", "convert", "webp", "jpeg", "png", "compress", "design"],
  },
  {
    id: "og-maker",
    number: "025",
    name: "OG Image Maker",
    description: "Design OpenGraph social cards visually.",
    href: "/og-maker",
    category: "design",
    keywords: ["image", "og", "social", "card", "design"],
  },
  {
    id: "ascii-banner",
    number: "026",
    name: "ASCII Banner",
    description: "Generate ASCII text art for terminal tools.",
    href: "/ascii-banner",
    category: "design",
    keywords: ["ascii", "text", "banner", "cli", "design"],
  },
  {
    id: "retro-crt",
    number: "027",
    name: "Retro CRT Text",
    description: "Generate retro CRT and glitch text effects.",
    href: "/retro-crt",
    category: "fun",
    keywords: ["retro", "crt", "glitch", "text", "css", "fun"],
  },

  // Product & Text Tools
  {
    id: "lorem-ipsum",
    number: "028",
    name: "Lorem Ipsum",
    description: "Generate placeholder text paragraphs and words.",
    href: "/lorem-ipsum",
    category: "product",
    keywords: ["text", "lorem", "ipsum", "placeholder", "generator"],
  },
  {
    id: "text-analyzer",
    number: "029",
    name: "Text Analyzer",
    description: "Count words, characters, and estimate reading time.",
    href: "/text-analyzer",
    category: "product",
    keywords: ["text", "word", "character", "count", "analyzer", "reading"],
  },
  {
    id: "qr-code",
    number: "030",
    name: "QR Code Generator",
    description: "Create and download customizable QR codes.",
    href: "/qr-code",
    category: "product",
    keywords: ["qr", "code", "generator", "link", "url"],
  },
  {
    id: "url-parser",
    number: "031",
    name: "URL Parser",
    description: "Deconstruct URLs into their component parts.",
    href: "/url-parser",
    category: "product",
    keywords: ["url", "parser", "uri", "query", "parameters"],
  },
  {
    id: "utm-builder",
    number: "032",
    name: "UTM Builder",
    description: "Build URLs with UTM parameters for tracking.",
    href: "/utm-builder",
    category: "product",
    keywords: ["utm", "url", "campaign", "tracking", "marketing"],
  },
  {
    id: "number-base",
    number: "033",
    name: "Number Base Converter",
    description: "Convert between Decimal, Hex, Binary, and Octal.",
    href: "/number-base",
    category: "product",
    keywords: ["number", "base", "hex", "decimal", "binary", "octal", "converter"],
  },
  {
    id: "base64-file",
    number: "034",
    name: "Base64 File Encoder",
    description: "Convert files and images into Base64 Data URIs.",
    href: "/base64-file",
    category: "product",
    keywords: ["file", "base64", "encoder", "data", "uri"],
  },
  {
    id: "pomodoro",
    number: "035",
    name: "Pomodoro Timer",
    description: "Customizable local Pomodoro focus timer.",
    href: "/pomodoro",
    category: "product",
    keywords: ["pomodoro", "timer", "focus", "productivity"],
  },
  {
    id: "svg-placeholder",
    number: "036",
    name: "SVG Placeholder",
    description: "Generate SVG placeholder images with custom dimensions.",
    href: "/svg-placeholder",
    category: "product",
    keywords: ["svg", "placeholder", "image", "generator", "mockup"],
  },
  {
    id: "string-obfuscator",
    number: "037",
    name: "String Obfuscator",
    description: "Obfuscate text with ROT13 and Zero-Width characters.",
    href: "/string-obfuscator",
    category: "product",
    keywords: ["string", "obfuscator", "rot13", "zero-width", "crypto"],
  },

  // Fun & Misc Tools
  {
    id: "password-strength",
    number: "038",
    name: "Password Strength Meter",
    description: "Evaluate password entropy and strength locally.",
    href: "/password-strength",
    category: "product",
    keywords: ["password", "strength", "entropy", "security", "zxcvbn"],
  },
  {
    id: "bcrypt-generator",
    number: "039",
    name: "Bcrypt Generator",
    description: "Hash and verify strings with bcrypt in your browser.",
    href: "/bcrypt-generator",
    category: "dev",
    keywords: ["bcrypt", "hash", "generator", "crypto", "password"],
  },
  {
    id: "css-triangle",
    number: "040",
    name: "CSS Triangle Generator",
    description: "Visual tool to generate CSS code for triangles.",
    href: "/css-triangle",
    category: "design",
    keywords: ["css", "triangle", "generator", "visual", "shape"],
  },
  {
    id: "json-to-ts",
    number: "041",
    name: "JSON to TypeScript",
    description: "Convert JSON objects into TypeScript interfaces.",
    href: "/json-to-ts",
    category: "dev",
    keywords: ["json", "typescript", "ts", "interface", "converter"],
  },
  {
    id: "rsa-key-generator",
    number: "042",
    name: "RSA Key Generator",
    description: "Generate RSA public and private key pairs locally.",
    href: "/rsa-key-generator",
    category: "dev",
    keywords: ["rsa", "key", "pair", "generator", "crypto", "security"],
  },
  {
    id: "meta-tag-generator",
    number: "043",
    name: "Meta Tag Generator",
    description: "Generate standard and OpenGraph HTML meta tags.",
    href: "/meta-tag-generator",
    category: "dev",
    keywords: ["meta", "tag", "generator", "seo", "html", "opengraph"],
  },
  {
    id: "device-info",
    number: "044",
    name: "Device & Browser Info",
    description: "Display your current device and browser capabilities.",
    href: "/device-info",
    category: "product",
    keywords: ["device", "browser", "info", "user-agent", "screen", "resolution"],
  },
  {
    id: "css-cursors",
    number: "045",
    name: "CSS Cursors Playground",
    description: "Interactive playground showing all CSS cursor properties.",
    href: "/css-cursors",
    category: "fun",
    keywords: ["css", "cursor", "playground", "interactive", "fun"],
  },
  {
    id: "text-to-speech",
    number: "046",
    name: "Text to Speech",
    description: "Use browser synthesis to read text aloud.",
    href: "/text-to-speech",
    category: "fun",
    keywords: ["text", "speech", "tts", "synthesis", "reader"],
  },
  {
    id: "bpm-tapper",
    number: "047",
    name: "BPM Tapper",
    description: "Tap to calculate Beats Per Minute.",
    href: "/bpm-tapper",
    category: "fun",
    keywords: ["bpm", "tapper", "music", "beats", "minute", "tempo"],
  },
  {
    id: "stopwatch",
    number: "048",
    name: "Stopwatch",
    description: "A simple, precise stopwatch with lap functionality.",
    href: "/stopwatch",
    category: "fun",
    keywords: ["stopwatch", "timer", "lap", "time", "clock"],
  },
  {
    id: "random-picker",
    number: "049",
    name: "Random Choice Picker",
    description: "Enter a list and let the tool pick one randomly.",
    href: "/random-picker",
    category: "fun",
    keywords: ["random", "choice", "picker", "list", "roulette"],
  },
  {
    id: "ascii-image",
    number: "050",
    name: "ASCII Image Art",
    description: "Upload an image and convert it to ASCII art.",
    href: "/ascii-image",
    category: "fun",
    keywords: ["ascii", "image", "art", "converter", "fun"],
  },
  // Added Parity Tools
  {
    id: "css-tailwind",
    number: "051",
    name: "CSS ↔ Tailwind",
    description: "Convert CSS to Tailwind utility classes.",
    href: "/css-tailwind",
    category: "dev",
    keywords: ["css", "tailwind", "converter", "utility", "dev"],
  },
  {
    id: "curl-to-fetch",
    number: "052",
    name: "Curl ↔ Fetch",
    description: "Convert cURL commands to fetch snippets.",
    href: "/curl-to-fetch",
    category: "dev",
    keywords: ["curl", "fetch", "http", "api", "dev"],
  },
  {
    id: "timezone-converter",
    number: "053",
    name: "Timezone Converter",
    description: "Convert dates across global timezones.",
    href: "/timezone-converter",
    category: "dev",
    keywords: ["time", "timezone", "converter", "world", "dev"],
  },
  {
    id: "svg-optimizer",
    number: "054",
    name: "SVG Optimizer",
    description: "Minify and clean SVG code.",
    href: "/svg-optimizer",
    category: "design",
    keywords: ["svg", "optimizer", "minify", "clean", "design"],
  },
  {
    id: "invoice-creator",
    number: "055",
    name: "Invoice Creator",
    description: "Build and print a professional invoice.",
    href: "/invoice-creator",
    category: "design",
    keywords: ["invoice", "creator", "bill", "pdf", "design"],
  },
  {
    id: "image-to-pdf",
    number: "056",
    name: "Image to PDF",
    description: "Convert images to a single PDF document.",
    href: "/image-to-pdf",
    category: "product",
    keywords: ["image", "pdf", "converter", "merge"],
  },
  {
    id: "pdf-merger",
    number: "057",
    name: "PDF Merger",
    description: "Combine multiple PDF files locally.",
    href: "/pdf-merger",
    category: "product",
    keywords: ["pdf", "merger", "combine", "join"],
  },
  {
    id: "pdf-splitter",
    number: "058",
    name: "PDF Splitter",
    description: "Extract specific pages from a PDF.",
    href: "/pdf-splitter",
    category: "product",
    keywords: ["pdf", "splitter", "extract", "pages"],
  },
  {
    id: "pdf-resizer",
    number: "059",
    name: "PDF Page Resizer",
    description: "Scale PDF pages to standard sizes.",
    href: "/pdf-resizer",
    category: "product",
    keywords: ["pdf", "resizer", "scale", "A4", "letter"],
  },
  {
    id: "pdf-password",
    number: "060",
    name: "PDF Password Remover",
    description: "Remove encryption from a known PDF.",
    href: "/pdf-password",
    category: "product",
    keywords: ["pdf", "password", "remover", "unlock"],
  },
  {
    id: "fake-data",
    number: "061",
    name: "Fake Data Generator",
    description: "Generate mock user data (JSON).",
    href: "/fake-data",
    category: "product",
    keywords: ["fake", "data", "mock", "generator", "json"],
  },
  {
    id: "exif-scrubber",
    number: "062",
    name: "EXIF Scrubber",
    description: "Remove EXIF metadata from images.",
    href: "/exif-scrubber",
    category: "product",
    keywords: ["exif", "metadata", "scrubber", "image", "privacy"],
  },
  {
    id: "secret-sharing",
    number: "063",
    name: "Secret Sharing",
    description: "Encrypt and share a secret via URL.",
    href: "/secret-sharing",
    category: "product",
    keywords: ["secret", "share", "crypto", "encrypt", "url"],
  },
  {
    id: "readability",
    number: "064",
    name: "Readability Analyzer",
    description: "Calculate Flesch Reading Ease score.",
    href: "/readability",
    category: "product",
    keywords: ["readability", "flesch", "analyzer", "text"],
  },
  {
    id: "calculators",
    number: "065",
    name: "Calculators",
    description: "Quick aspect ratio and percentage math.",
    href: "/calculators",
    category: "product",
    keywords: ["calculator", "math", "aspect", "ratio", "percentage"],
  },
  {
    id: "number-namer",
    number: "066",
    name: "Number Namer",
    description: "Convert numbers into English words.",
    href: "/number-namer",
    category: "fun",
    keywords: ["number", "namer", "words", "english"],
  },
  {
    id: "typing-test",
    number: "067",
    name: "Typing Test",
    description: "Check your WPM typing speed.",
    href: "/typing-test",
    category: "fun",
    keywords: ["typing", "test", "wpm", "speed", "keyboard"],
  },
  {
    id: "fancy-text",
    number: "068",
    name: "Fancy Text",
    description: "Convert text to fancy Unicode variations.",
    href: "/fancy-text",
    category: "fun",
    keywords: ["fancy", "text", "unicode", "font", "generator"],
  },
];
